const fileCategories = [
  "Resume / CV",
  "Coding / Bash",
  "Cover Letter / Job Application",
  "Invoice / Bill / Receipt",
  "Legal Document / Contract / Agreement",
  "Medical Report / Prescription",
  "Bank Statement / Financial Document",
  "Tax Document / Salary Slip",
  "Meeting Notes / Minutes of Meeting (MoM)",
  "Project Proposal / Specification Document",
  "Educational Material / Lecture Notes",
  "Certificate / Degree / Academic Proof",
  "Research Paper / Whitepaper",
  "API Documentation",
  "Technical Guide / README",
  "Docker / Kubernetes / DevOps File",
  "CI/CD Config File (e.g., GitHub Actions, Jenkins)",
  "System Architecture Diagram / Infrastructure Plan",
  "Source Code Snippet / Script File",
  "User Manual / Instructional Guide",
  "Marketing Plan / Business Strategy",
  "Pitch Deck / Investor Presentation",
  "Data Analysis Report / Dashboard Export",
  "Travel Document / Itinerary / Tickets",
  "Image / Screenshot / Media Asset",
  "Presentation / Slide Deck",
];

export default fileCategories;
